export enum ApiErrorEnum {
  api_error_user_not_found = 0,
  api_error_credential_invalid = 1,
  api_error_user_already_exist = 2,
  api_error_invalid_input_data = 3,
  api_error_unauthorized = 4,
  api_error_agreement_not_accepted = 5,
  api_error_invalid_token = 6,
  api_error_email_already_exist = 7,
  api_error_no_file_uploaded = 12,
  api_error_password_not_match = 14,
  api_error_company_already_exist = 15,
  api_error_company_not_found = 16,
  api_error_username_already_exist = 17,
  api_error_internal_server_error = 18,
  api_error_company_owner_already_exists = 19,
  api_error_company_staff_already_exists = 20,
  api_error_company_owner_not_found = 21,
  api_error_no_update_fields_provided = 22,
  api_error_company_staff_not_found = 23,
  api_error_failed_to_upload_files = 24,
  api_error_company_not_updated = 25,
  api_error_companyOwner_not_found = 26,
  api_error_companyStaff_not_found = 27,
  api_error_playlist_not_found = 28,
  api_error_song_not_found = 29,
  api_error_song_already_exist = 30,
}
