export enum ApiErrorEnum {
  api_error_user_not_found = 0,
  api_error_credential_invalid = 1,
  api_error_user_already_exist = 2,
  api_error_invalid_input_data = 3,
  api_error_unauthorized = 4,
  api_error_agreement_not_accepted = 5,
  api_error_invalid_token = 6,
  api_error_email_already_exist = 7,
  api_error_no_file_uploaded = 12,
  api_error_password_not_match = 14,
  api_error_company_already_exist = 15,
  api_error_company_not_found = 16,
  api_error_username_already_exist = 17,
  api_error_company_not_updated = 18,
  api_error_companyOwner_not_found = 19,
  api_error_companyStaff_not_found = 20,
  api_error_playlist_not_found = 21,
  api_error_song_not_found = 22,
  api_error_song_already_exist = 23,
}
