export const SpotifyConstants = {
  client_id: 'cbd591920f044b0681deb59897d4b152',
  client_secret: 'b7a55c55aae84202828fb7c89a56b8ac',
  // redirectUri: 'https://google.com',
  redirectUri: 'http://172.20.10.3:3000/spotify/deneme',
  // redirectUri: 'http://localhost:3000/spotify/deneme',
  scope: [
    'user-read-playback-state',
    'user-modify-playback-state',
    'user-read-currently-playing',
    'app-remote-control',
    'streaming',
    'playlist-read-private',
    'playlist-read-collaborative',
    'playlist-modify-private',
    'playlist-modify-public',
    'user-read-playback-position',
    'user-top-read',
    'user-read-recently-played',
    'user-library-modify',
    'user-library-read',
    'user-read-email',
    'user-read-private',
  ],
  state: 'jhfgkagfkjyeawgfdasfaewfsdc',
};
